### ISSUE TITLE
Using hot corner also displays slow keys notice

### ISSUE THREAD

**Issue by dessington** [Leinnan/lwa-hot-corners#3]
I've integrated this into DXT3 with the following conf and it works well. There is just one small issue when using bottom-right corner - it displays a notice about slow keys, which is disabled. Any advice to get rid of this notice? Any help is appreciated. It also only seems to show the notice the first time the corner is used, after that it doesn't appear.

top_left_command=
top_right_command=xfce4-terminal -e 'sudo /usr/share/dxt3/update'
bottom_left_command=
bottom_right_command=xdotool key ctrl+alt+d
hold_duration=250
disable_on_fullscreen=true

**Comment by Leinnan** [comment]
You can skip empty commands. I will try to add today that when command is empty nothing should happened.

**Comment by dessington** [comment]
Thank you much appreciated.

**Comment by Leinnan** [comment]
I've updated source code, try get newest version and check if there is any change.
